export const kodamList = [
  "macan kumbang",
  "macan lembu",
  "macan bunting",
  "macan cacat",
  "kucing butut",
  "kucing kampung",
  "kucing blawor",
  "kucing kampret",
  "Harimau Putih",
  "Naga Merah",
  "Serigala Hitam",
  "Burung Hantu",
  "Kuntilanak",
  "Macan Tutul",
  "Kuda Nil",
  "Siluman Ular",
  "Kucing Hitam",
  "Hantu Pocong",
  "Burung Garuda",
  "Siluman Kera",
  "Sundel Bolong",
  "Laba-laba Raksasa",
  "Gajah Putih",
  "Siluman Serigala",
  "Hantu Perempuan",
  "Rusa Emas",
  "Hantu Jerangkong",
  "Siluman Harimau",
  "Merpati Putih",
  "Jin Hutan",
  "Elang Hitam",
  "Hantu Laut",
  "Siluman Kelelawar",
  "Hantu Wanita Tua",
  "Siluman Buaya",
  "Serigala Putih",
  "Siluman Anjing",
  "Hantu Hitam",
  "Harimau Hitam",
  "Siluman Kucing",
  "Hantu Perawan",
  "Burung Rajawali",
  "Siluman Tikus",
  "Naga Hitam",
  "Kuntilanak Merah",
  "Ular Emas",
  "Siluman Kelelawar",
  "Hantu Berambut Panjang",
  "Serigala Emas",
  "Hantu Jepang",
  "Harimau Merah",
  "Siluman Ikan",
  "Hantu Nyai Roro Kidul",
  "Siluman Burung",
  "Serigala Hitam",
  "Jin Penunggu",
  "Hantu Cantik",
  "Siluman Harimau",
  "Ular Hitam",
  "Siluman Beruang",
  "Hantu Air",
  "Burung Hantu Putih",
  "Siluman Ikan",
  "Hantu Nenek",
  "Ular Hitam",
  "Hantu Gadis",
  "Harimau Putih",
  "Siluman Ular",
  "Serigala Putih",
  "Hantu Perempuan",
  "Naga Emas",
  "Burung Garuda",
  "Siluman Harimau",
  "Kelelawar Hitam",
  "Hantu Jerangkong",
  "Siluman Macan",
  "Jin Penjaga",
  "Hantu Nenek",
  "Siluman Anjing",
  "Harimau Merah",
  "Hantu Perempuan",
  "Jin Penunggu",
  "Burung Hantu",
  "Serigala Putih",
  "Siluman Ular",
  "Hantu Wanita Tua",
  "Siluman Buaya",
  "Harimau Putih",
  "Naga Merah",
  "Serigala Hitam",
  "Kuntilanak",
  "Macan Tutul",
  "Kuda Nil",
  "Siluman Ular",
  "Kucing Hitam",
  "Hantu Pocong",
  "Burung Garuda",
  "Siluman Kera",
  "Sundel Bolong",
  "Laba-laba Raksasa",
  "Gajah Putih",
  "Siluman Serigala",
  "Hantu Perempuan",
  "Rusa Emas",
  "Hantu Jerangkong",
  "Siluman Harimau",
  "Merpati Putih",
  "Jin Hutan",
  "Burung Elang",
  "Harimau Putih",
  "Kuntilanak",
  "Siluman Kucing",
  "Naga Hitam",
  "Burung Hantu",
  "Harimau Merah",
  "Kuntilanak Putih",
  "Siluman Serigala",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Hantu Perempuan",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
  "Harimau Hitam",
  "Burung Garuda",
  "Kuntilanak Merah",
  "Siluman Ular",
  "Burung Hantu",
  "Harimau Emas",
  "Naga Merah",
  "Kuntilanak Putih",
  "Burung Hantu",
  "Harimau Putih",
  "Siluman Kucing",
  "Naga Hitam",
  "Harimau Merah",
  "Kuntilanak",
  "Siluman Serigala",
  "Burung Garuda",
  "Kuntilanak Putih",
  "Harimau Hitam",
  "Burung Rajawali",
  "Kucing Hitam",
  "Hantu Perempuan",
  "Naga Putih",
];

export const specialKodamList = [
"Phoenix Api",
"Naga Es",
"Kuda Pegasi",
"Serigala Hitam Bertanduk",
"Burung Garuda Emas",
"Hantu Pelindung",
"Macan Awan",
"Siluman Kelelawar Raksasa",
"Ular Naga Api",
"Kura-Kura Raksasa",
"Burung Merak Biru",
"Harimau Bersayap",
"Kijang Perak",
"Singa Putih",
"Jin Api",
"Elang Petir",
"Kuda Bertanduk",
"Burung Hantu Mata Biru",
"Gajah Berkaki Enam",
"Hantu Kabut",
"Siluman Harimau Perak",
"Ular Bermata Seribu",
"Burung Rajawali Raksasa",
"Harimau Bertanduk Emas",
"Naga Bermata Biru",
"Hantu Air",
"Siluman Rubah Api",
"Kucing Emas",
"Burung Merpati Hitam",
"Kuda Berbulu Perak",
"Burung Hantu Bertanduk",
"Harimau Hitam Bercahaya",
"Naga Langit",
"Jin Penjaga Gerbang",
"Siluman Ikan Duyung",
"Burung Elang Emas",
"Harimau Biru",
"Kuda Api",
"Hantu Pemburu",
"Siluman Serigala Putih",
"Kijang Emas",
"Burung Rajawali Hitam",
"Naga Laut",
"Harimau Bermata Merah",
"Ular Perak",
"Jin Hutan",
"Burung Hantu Biru",
"Kucing Bersayap",
"Singa Api",
"Hantu Pohon",
"Naga Emas",
"Harimau Berkepala Dua",
"Siluman Kelelawar",
"Ular Bercahaya",
"Burung Phoenix",
"Harimau Berkaki Enam",
"Kuda Naga",
"Burung Rajawali Api",
"Kucing Mata Merah",
"Naga Hijau",
"Harimau Bersayap",
"Elang Bersayap Emas",
"Siluman Singa",
"Ular Berkepala Tiga",
"Hantu Bayangan",
"Burung Hantu Hitam",
"Kuda Emas",
"Harimau Biru",
"Jin Penjaga Harta",
"Naga Bercahaya",
"Burung Rajawali Petir",
"Siluman Serigala Hitam",
"Ular Terbang",
"Kucing Bersayap",
"Harimau Api",
"Hantu Es",
"Burung Garuda Api",
"Kuda Laut",
"Siluman Kelelawar Merah",
"Naga Bintang",
"Harimau Berkepala Singa",
"Ular Mata Hijau",
"Burung Rajawali Putih",
"Kucing Berkaki Delapan",
"Harimau Air",
"Jin Petir",
"Naga Api",
"Burung Hantu Perak",
"Kuda Raksasa",
"Siluman Serigala Bercahaya",
"Harimau Petir",
"Elang Berbulu Emas",
"Ular Naga",
"Burung Rajawali Biru",
"Kuda Mata Biru",
"Siluman Singa Putih",
"Naga Kuning",
"Harimau Emas",
"Burung Garuda Laut",
"Jin Api Merah"
];
